version: "3.8"
services:
### Postgres Database ###
  postgres:
    image: postgres:9.6.24
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_USER: pc
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: special_department_db
### Postgres Adminer ###
  postgres_admin:
    image: dpage/pgadmin4:6
    depends_on:
      - postgres
    environment: 
      PGADMIN_DEFAULT_EMAIL: admin@admin.hu
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
### API Spring Boot ###
  api:
    build:
      dockerfile: Dockerfile
      context: ./
    depends_on: 
      - postgres
    environment: 
      DATABASE_URL: postgresql://postgres:5432/special_department_db
      DATABASE_USER: pc
      DATABASE_PASSWORD: 123
    ports:
      - "8080:8080"